### PR TITLE
RandomFood API

### PR DESCRIPTION
**Pull request by mukeshmjn**
## Description

I used random food api .
endpoint:- https://foodish-api.herokuapp.com/api/

## Screenshot 
image

<hr>
Checklist

- [x] API used in this PR was not used in just-calling-random-api before.
- [x] API used in this PR is Public or I have permission to use it.
- [x] My contribution is working.
- [x] My contribution doesn't expose any API keys.
- [x] My changes don't generate any new warnings.
- [x] My changes don't affect any work done by other developers. 

To tick a box, replace `[ ]` with `[x]`.

### CODE REVIEW

**Review by vedangj044 — APPROVED** [review]

**Comment by vedangj044** [comment]
Thanks for the PR.

**Comment by mukeshmjn** [comment]
@vedangj044 project got excluded from hactoberfest..

**Comment by vedangj044** [comment]
@mukeshmjn I beg to differ, all prs are there. Communicate in gitter if u are facing any issues https://gitter.im/JustCallingRandomAPI/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by mukeshmjn** [comment]
@vedangj044 it shows in hactoberfest dashboard that project is excluded

**Comment by vedangj044** [comment]
Share the screenshot please

**Comment by mukeshmjn** [comment]
Cap
check it out...your project is excluded .... ;(

**Comment by vedangj044** [comment]
This is your fork. My repo is `vedangj044/just-calling-random-api `. 
The screenshot you shared is regarding a PR done to your fork and it won't count. Only accepted PRs to my for ( repo ) would count.

**Comment by mukeshmjn** [comment]
@vedangj044 oh sorry , i got confused sorry for misunderstanding...Can i make more PR's by making more api requests?

**Comment by vedangj044** [comment]
No problem 😊. Yes, you can add more APIs, but do it only if you think you would learn something new.

**Comment by mukeshmjn** [comment]
@vedangj044 ok thanks!

**Pull request merged**
