### PR TITLE
added giphy api

### PR DESCRIPTION
**Pull request by dddqwerty**
## Description

I added Giphy API which is show 5 GIFS according to search value.

<hr>
Checklist

- [x] API used in this PR was not used in just-calling-random-api before.
- [x] API used in this PR is Public or I have permission to use it.
- [x] My contribution is working.
- [x] My contribution doesn't expose any API keys.
- [x] My changes don't generate any new warnings.
- [x] My changes don't affect any work done by other developers. 

To tick a box, replace `[ ]` with `[x]`.

### CODE REVIEW

**Comment by dddqwerty** [comment]
This pr is for hacktoberfest but i don't know how to add labels.

**Comment by vedangj044** [comment]
Hello, I can't merge PR which exposes key. I would request you to disable the key you have added in the PR. And follow these instructions ( https://dev.to/thepuskar/how-to-hide-your-api-keys-in-react-4k55 ) to hide the API key. You must use "GIPHY_KEY" as your environment variable, I would add it to the repository secrets. 

PS: Kindly disable the exposed API keys. 
Thank you

**Comment by dddqwerty** [comment]
Okay thanks.

**Review by vedangj044 — APPROVED** [review]

**Comment by vedangj044** [comment]
Thanks for the PR

**Pull request merged**
