### PR TITLE
Abstractapi

### PR DESCRIPTION
**Pull request by MuditWadhwa**
I have used the Abstract API to allow the user to know whether a particular day in India is a public Holiday or not.It is present at the end of the page. Please view it and merge the PR to confirm my contribution to the project.

### CODE REVIEW

**Comment by vedangj044** [comment]
Thanks for the PR. Can you try resolving the merge conflicts? You can follow the command line instructions provided there.

**Comment by MuditWadhwa** [comment]
Hey...Could you please give some clarity on how could these merge conflicts be solved?I have tried a lot but it works fine on my local machine....

**Comment by vedangj044** [comment]
No problem, To resolve a merge conflict you first need to sync a fork ( https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork ) and then rebase your branch accordingly, for now, I have resolved them and merged the PR.

**Comment by MuditWadhwa** [comment]
Thanks a lot for assuring me that the issue was solved.I learned a lot from this project.Thanks for the advice as well as the learning experience!

**Comment by vedangj044** [comment]
Thanks for the kind words !

**Pull request merged**
